<?php


// Translation of file /modules/tags/module.php

$_COS_LANG_MODULE['tags_error_no_title'] = 'Ingen titel';
$_COS_LANG_MODULE['tags_submit_add_another'] = 'Tilføj endnu et tag';
$_COS_LANG_MODULE['tags_added_tag_action_message'] = 'Tag er tilføjet';
$_COS_LANG_MODULE['tags_updated_tag_action_message'] = 'Tag er opdateret';
$_COS_LANG_MODULE['tags_deleted_tag_action_message'] = 'Tag er slettet';
$_COS_LANG_MODULE['tags_admin_edit'] = 'Ret';
$_COS_LANG_MODULE['tags_admin_delete'] = 'Slet';
$_COS_LANG_MODULE['tags_label'] = 'Tags';
$_COS_LANG_MODULE['tags_title'] = 'Tags';

// Translation of file /modules/tags/blocks/tags.inc

$_COS_LANG_MODULE['tags_main'] = 'tags_main';

// Translation of file /modules/tags/views/add.inc

$_COS_LANG_MODULE['tags_add_tags_legend'] = 'Tilføj Tag';
$_COS_LANG_MODULE['tags_label_title'] = 'Titel';
$_COS_LANG_MODULE['tags_is_main'] = 'Hoved tag';
$_COS_LANG_MODULE['tags_label_description'] = 'Beskrivelse';
$_COS_LANG_MODULE['tags_submit_add'] = 'Tilføj';

// Translation of file /modules/tags/views/edit.inc

$_COS_LANG_MODULE['tags_submit_update'] = 'Opdater';

// Translation of file /modules/tags/views/delete.inc

$_COS_LANG_MODULE['tags_delete_tags_legend'] = 'Slet tag';
$_COS_LANG_MODULE['tags_submit_delete'] = 'Slet';
