<?php

// Translation of file /home/dennis/www/oscmsdk/modules/tags/views/delete.inc

$_COS_LANG_MODULE['tags_delete_tags_legend'] = 'Slet tag';
$_COS_LANG_MODULE['tags_submit_delete'] = 'Slet';
// Translation of file /home/dennis/www/oscmsdk/modules/tags/views/add.inc

$_COS_LANG_MODULE['tags_add_tags_legend'] = 'Tilføj Tag';
$_COS_LANG_MODULE['tags_label_title'] = 'Titel';
$_COS_LANG_MODULE['tags_is_main'] = 'Tag er overordnet';
$_COS_LANG_MODULE['tags_label_description'] = 'Beskrivelse';
$_COS_LANG_MODULE['tags_submit_add_another'] = 'Tilføj endnu et tag';
$_COS_LANG_MODULE['tags_submit_add'] = 'Tilføj';
// Translation of file /home/dennis/www/oscmsdk/modules/tags/views/edit.inc

$_COS_LANG_MODULE['tags_submit_update'] = 'Opdater';
// Translation of file /home/dennis/www/oscmsdk/modules/tags/blocks/tags.inc

$_COS_LANG_MODULE['tags_main'] = 'Hoved Tags';
// Translation of file /home/dennis/www/oscmsdk/modules/tags/model.tags.inc

$_COS_LANG_MODULE['tags_error_no_title'] = 'Ingen titel';
$_COS_LANG_MODULE['tags_added_tag_action_message'] = 'Tag er tilføjet';
$_COS_LANG_MODULE['tags_updated_tag_action_message'] = 'Tag er opdateret';
$_COS_LANG_MODULE['tags_deleted_tag_action_message'] = 'Tag er slettet';
$_COS_LANG_MODULE['tags_admin_edit'] = 'Ret';
$_COS_LANG_MODULE['tags_admin_delete'] = 'Slet';
