<?php

$_COS_LANG_MODULE['tags_error_no_title'] = '无标题';
$_COS_LANG_MODULE['tags_submit_add_another'] = '添加另一个';
$_COS_LANG_MODULE['tags_added_tag_action_message'] = '添加标签';
$_COS_LANG_MODULE['tags_updated_tag_action_message'] = '标签更新';
$_COS_LANG_MODULE['tags_deleted_tag_action_message'] = '标签删除';
$_COS_LANG_MODULE['tags_admin_edit'] = '编辑';
$_COS_LANG_MODULE['tags_admin_delete'] = '删除';
$_COS_LANG_MODULE['tags_label'] = '标签';
$_COS_LANG_MODULE['Tags'] = '标签';
$_COS_LANG_MODULE['Tags has been deleted!'] = '标签已被删除！';
$_COS_LANG_MODULE['Not sufficient privileges. Super user is required'] = '没有足够的权限。超级用户需要';
$_COS_LANG_MODULE['tags_delete_tags_legend'] = '删除标签';
$_COS_LANG_MODULE['tags_submit_delete'] = '删除';
$_COS_LANG_MODULE['tags_add_tags_legend'] = '添加标签';
$_COS_LANG_MODULE['tags_label_title'] = '标题';
$_COS_LANG_MODULE['tags_is_main'] = '主标签';
$_COS_LANG_MODULE['tags_label_description'] = '描述';
$_COS_LANG_MODULE['tags_submit_add'] = '加';
$_COS_LANG_MODULE['tags_submit_update'] = '更新';
$_COS_LANG_MODULE['tags_main'] = '主要是标签';
