<?php

$_COS_LANG_MODULE['No title'] = '无题';
$_COS_LANG_MODULE['Add another'] = '添加另一个';
$_COS_LANG_MODULE['Tag has been added'] = '标签已添加';
$_COS_LANG_MODULE['Tag has been updated'] = '标签已更新';
$_COS_LANG_MODULE['Tag has been deleted'] = '标签已被删除';
$_COS_LANG_MODULE['Edit'] = '编辑';
$_COS_LANG_MODULE['Delete'] = '删除';
$_COS_LANG_MODULE['Tags'] = '标签';
$_COS_LANG_MODULE['Tags has been deleted!'] = '标签已被删除！';
$_COS_LANG_MODULE['Not sufficient privileges. Super user is required'] = '没有足够的权限。超级用户需要';
$_COS_LANG_MODULE['Delete tag'] = '删除标签';
$_COS_LANG_MODULE['Add a tag'] = '添加标签';
$_COS_LANG_MODULE['Title'] = '称号';
$_COS_LANG_MODULE['Is a main tag'] = '是一家主营标签';
$_COS_LANG_MODULE['Description'] = '描述';
$_COS_LANG_MODULE['Submit'] = '提交';
$_COS_LANG_MODULE['Edit tag'] = '编辑标签';
$_COS_LANG_MODULE['Update'] = '更新';
$_COS_LANG_MODULE['Main tags'] = '主要标签';
