<?php


// Translation of file /modules/tags/module.php

$_COS_LANG_MODULE['tags_error_no_title'] = 'tags_error_no_title';
$_COS_LANG_MODULE['tags_submit_add_another'] = 'tags_submit_add_another';
$_COS_LANG_MODULE['tags_added_tag_action_message'] = 'tags_added_tag_action_message';
$_COS_LANG_MODULE['tags_updated_tag_action_message'] = 'tags_updated_tag_action_message';
$_COS_LANG_MODULE['tags_deleted_tag_action_message'] = 'tags_deleted_tag_action_message';
$_COS_LANG_MODULE['tags_admin_edit'] = 'tags_admin_edit';
$_COS_LANG_MODULE['tags_admin_delete'] = 'tags_admin_delete';
$_COS_LANG_MODULE['tags_label'] = 'tags_label';
$_COS_LANG_MODULE['Tags'] = 'Tags';

// Translation of file /modules/tags/api/module.php

$_COS_LANG_MODULE['Tags has been deleted!'] = 'Tags has been deleted!';
$_COS_LANG_MODULE['Not sufficient privileges. Super user is required'] = 'Not sufficient privileges. Super user is required';

// Translation of file /modules/tags/views/delete.inc

$_COS_LANG_MODULE['tags_delete_tags_legend'] = 'tags_delete_tags_legend';
$_COS_LANG_MODULE['tags_submit_delete'] = 'tags_submit_delete';

// Translation of file /modules/tags/views/add.inc

$_COS_LANG_MODULE['tags_add_tags_legend'] = 'tags_add_tags_legend';
$_COS_LANG_MODULE['tags_label_title'] = 'tags_label_title';
$_COS_LANG_MODULE['tags_is_main'] = 'tags_is_main';
$_COS_LANG_MODULE['tags_label_description'] = 'tags_label_description';
$_COS_LANG_MODULE['tags_submit_add'] = 'tags_submit_add';

// Translation of file /modules/tags/views/edit.inc

$_COS_LANG_MODULE['tags_submit_update'] = 'tags_submit_update';

// Translation of file /modules/tags/blocks/tags.inc

$_COS_LANG_MODULE['tags_main'] = 'tags_main';
