<?php


// Translation of file /modules/tags/module.php

$_COS_LANG_MODULE['tags_error_no_title'] = 'tags_error_no_title';
$_COS_LANG_MODULE['Add another'] = 'Add another';
$_COS_LANG_MODULE['Tag has been added'] = 'Tag has been added';
$_COS_LANG_MODULE['Tag has been updated'] = 'Tag has been updated';
$_COS_LANG_MODULE['Tag has been deleted'] = 'Tag has been deleted';
$_COS_LANG_MODULE['Edit'] = 'Edit';
$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['tags_label'] = 'tags_label';
$_COS_LANG_MODULE['Tags'] = 'Tags';

// Translation of file /modules/tags/api/module.php

$_COS_LANG_MODULE['Tags has been deleted!'] = 'Tags has been deleted!';
$_COS_LANG_MODULE['Not sufficient privileges. Super user is required'] = 'Not sufficient privileges. Super user is required';

// Translation of file /modules/tags/views/delete.inc

$_COS_LANG_MODULE['Delete tag'] = 'Delete tag';

// Translation of file /modules/tags/views/add.inc

$_COS_LANG_MODULE['Add a tag'] = 'Add a tag';
$_COS_LANG_MODULE['Title'] = 'Title';
$_COS_LANG_MODULE['Is a main tag'] = 'Is a main tag';
$_COS_LANG_MODULE['Description'] = 'Description';
$_COS_LANG_MODULE['Submit'] = 'Submit';

// Translation of file /modules/tags/views/edit.inc

$_COS_LANG_MODULE['Edit tag'] = 'Edit tag';
$_COS_LANG_MODULE['Update'] = 'Update';

// Translation of file /modules/tags/blocks/tags.inc

$_COS_LANG_MODULE['tags_main'] = 'tags_main';
