<?php


// Translation of file /modules/tags/blocks/tags.inc

$_COS_LANG_MODULE['tags_main'] = 'tags_main';

// Translation of file /modules/tags/views/edit.inc

$_COS_LANG_MODULE['tags_add_tags_legend'] = 'Add Tag';
$_COS_LANG_MODULE['tags_label_title'] = 'Title';
$_COS_LANG_MODULE['tags_is_main'] = 'Main tag';
$_COS_LANG_MODULE['tags_label_description'] = 'Description';
$_COS_LANG_MODULE['tags_submit_update'] = 'Update';

// Translation of file /modules/tags/views/add.inc

$_COS_LANG_MODULE['tags_submit_add_another'] = 'Add Another';
$_COS_LANG_MODULE['tags_submit_add'] = 'Add';

// Translation of file /modules/tags/views/delete.inc

$_COS_LANG_MODULE['tags_delete_tags_legend'] = 'Delete Tag';
$_COS_LANG_MODULE['tags_submit_delete'] = 'Delete';

// Translation of file /modules/tags/module.php

$_COS_LANG_MODULE['tags_error_no_title'] = 'No title';
$_COS_LANG_MODULE['tags_added_tag_action_message'] = 'Tag Added';
$_COS_LANG_MODULE['tags_updated_tag_action_message'] = 'Tag Updated';
$_COS_LANG_MODULE['tags_deleted_tag_action_message'] = 'Tag Deleted';
$_COS_LANG_MODULE['tags_admin_edit'] = 'Edit';
$_COS_LANG_MODULE['tags_admin_delete'] = 'Delete';
$_COS_LANG_MODULE['blog_tags'] = 'blog_tags';
$_COS_LANG_MODULE['tags_title'] = 'Tags';
