<?php

$_COS_LANG_MODULE['No title'] = 'Ingen tittel';
$_COS_LANG_MODULE['Add another'] = 'Legg til en annen';
$_COS_LANG_MODULE['Tag has been added'] = 'Tag har blitt lagt';
$_COS_LANG_MODULE['Tag has been updated'] = 'Tag har blitt oppdatert';
$_COS_LANG_MODULE['Tag has been deleted'] = 'Tag er slettet';
$_COS_LANG_MODULE['Edit'] = 'Redigere';
$_COS_LANG_MODULE['Delete'] = 'Slett';
$_COS_LANG_MODULE['Tags'] = 'Tags';
$_COS_LANG_MODULE['Tags has been deleted!'] = 'Tags er blitt slettet!';
$_COS_LANG_MODULE['Not sufficient privileges. Super user is required'] = 'Ikke tilstrekkelige privilegier. Superbruker er nødvendig';
$_COS_LANG_MODULE['Delete tag'] = 'Slett tag';
$_COS_LANG_MODULE['Add a tag'] = 'Legg til et merke';
$_COS_LANG_MODULE['Title'] = 'Tittel';
$_COS_LANG_MODULE['Is a main tag'] = 'Er en hoved tag';
$_COS_LANG_MODULE['Description'] = 'Beskrivelse';
$_COS_LANG_MODULE['Submit'] = 'Send inn';
$_COS_LANG_MODULE['Edit tag'] = 'Edit tag';
$_COS_LANG_MODULE['Update'] = 'Oppdater';
$_COS_LANG_MODULE['Main tags'] = 'Hoved tags';
