<?php

$_COS_LANG_MODULE['tags_delete_tags_legend'] = 'Slett tag';
$_COS_LANG_MODULE['tags_submit_delete'] = 'Slett';
$_COS_LANG_MODULE['tags_add_tags_legend'] = 'Legg Tag';
$_COS_LANG_MODULE['tags_label_title'] = 'Tittel';
$_COS_LANG_MODULE['tags_is_main'] = 'Den viktigste taket';
$_COS_LANG_MODULE['tags_label_description'] = 'Beskrivelse';
$_COS_LANG_MODULE['tags_submit_add_another'] = 'Legg til en annen tag';
$_COS_LANG_MODULE['tags_submit_add'] = 'Legg';
$_COS_LANG_MODULE['tags_submit_update'] = 'Refresh';
$_COS_LANG_MODULE['tags_main'] = 'Viktige Tags';
$_COS_LANG_MODULE['tags_error_no_title'] = 'Ingen tittel';
$_COS_LANG_MODULE['tags_added_tag_action_message'] = 'Tag er lagt';
$_COS_LANG_MODULE['tags_updated_tag_action_message'] = 'Tag er oppdatert';
$_COS_LANG_MODULE['tags_deleted_tag_action_message'] = 'Tag er slettet';
$_COS_LANG_MODULE['tags_admin_edit'] = 'Rediger';
$_COS_LANG_MODULE['tags_admin_delete'] = 'Slett';
