<?php

$_COS_LANG_MODULE['tags_main'] = 'Ist Haupt Tag';
$_COS_LANG_MODULE['tags_add_tags_legend'] = 'Tag hinzufügen';
$_COS_LANG_MODULE['tags_label_title'] = 'Titel';
$_COS_LANG_MODULE['tags_is_main'] = 'Haupt Tag';
$_COS_LANG_MODULE['tags_label_description'] = 'Beschreibung';
$_COS_LANG_MODULE['tags_submit_update'] = 'Aktualisierung';
$_COS_LANG_MODULE['tags_submit_add_another'] = 'Ein weiteres hinzufügen';
$_COS_LANG_MODULE['tags_submit_add'] = 'Hinzufügen';
$_COS_LANG_MODULE['tags_delete_tags_legend'] = 'Tag löschen';
$_COS_LANG_MODULE['tags_submit_delete'] = 'Löschen';
$_COS_LANG_MODULE['tags_error_no_title'] = 'Kein Titel';
$_COS_LANG_MODULE['tags_added_tag_action_message'] = 'Hinzugefügt Tag';
$_COS_LANG_MODULE['tags_updated_tag_action_message'] = 'Aktualisiert Tag';
$_COS_LANG_MODULE['tags_deleted_tag_action_message'] = 'Tag gelöscht';
$_COS_LANG_MODULE['tags_admin_edit'] = 'Bearbeiten';
$_COS_LANG_MODULE['tags_admin_delete'] = 'Löschen';
$_COS_LANG_MODULE['tags_label'] = 'Schlagworte';
$_COS_LANG_MODULE['Tags'] = 'Schlagworte';
