<?php

$_COS_LANG_MODULE['tags_error_no_title'] = 'Kein Titel';
$_COS_LANG_MODULE['Add another'] = 'Neue hinzufügen';
$_COS_LANG_MODULE['Tag has been added'] = 'Tag hinzugefügt wurde';
$_COS_LANG_MODULE['Tag has been updated'] = 'Tag wurde aktualisiert';
$_COS_LANG_MODULE['Tag has been deleted'] = 'Tag wurde gelöscht';
$_COS_LANG_MODULE['Edit'] = 'Bearbeiten';
$_COS_LANG_MODULE['Delete'] = 'Löschen';
$_COS_LANG_MODULE['tags_label'] = 'Schlagworte';
$_COS_LANG_MODULE['Tags'] = 'Schlagworte';
$_COS_LANG_MODULE['Tags has been deleted!'] = 'Tags wurde gelöscht!';
$_COS_LANG_MODULE['Not sufficient privileges. Super user is required'] = 'Nicht ausreichende Berechtigungen. Super-Benutzer benötigt wird';
$_COS_LANG_MODULE['Delete tag'] = 'Tag löschen';
$_COS_LANG_MODULE['Add a tag'] = 'Add einen tag';
$_COS_LANG_MODULE['Title'] = 'Titel';
$_COS_LANG_MODULE['Is a main tag'] = 'Ist einer der wichtigsten Tag';
$_COS_LANG_MODULE['Description'] = 'Beschreibung';
$_COS_LANG_MODULE['Submit'] = 'Einreichen';
$_COS_LANG_MODULE['Edit tag'] = 'Tag bearbeiten';
$_COS_LANG_MODULE['Update'] = 'Aktualisierung';
$_COS_LANG_MODULE['tags_main'] = 'Ist Haupt Tag';
