<?php

$_COS_LANG_MODULE['No title'] = 'Ei otsikkoa';
$_COS_LANG_MODULE['Add another'] = 'Lisää toinen';
$_COS_LANG_MODULE['Tag has been added'] = 'Tunniste on lisätty';
$_COS_LANG_MODULE['Tag has been updated'] = 'Tag on päivitetty';
$_COS_LANG_MODULE['Tag has been deleted'] = 'Tag on poistettu';
$_COS_LANG_MODULE['Edit'] = 'Muokata';
$_COS_LANG_MODULE['Delete'] = 'Poistaa';
$_COS_LANG_MODULE['Tags'] = 'Tunnisteet';
$_COS_LANG_MODULE['Tags has been deleted!'] = 'Tunnisteet on poistettu!';
$_COS_LANG_MODULE['Not sufficient privileges. Super user is required'] = 'Ei riittäviä käyttöoikeuksia. Super Käyttäjä on velvollinen';
$_COS_LANG_MODULE['Delete tag'] = 'Poista tunniste';
$_COS_LANG_MODULE['Add a tag'] = 'Lisää tunniste';
$_COS_LANG_MODULE['Title'] = 'Otsikko';
$_COS_LANG_MODULE['Is a main tag'] = 'On tärkein tunniste';
$_COS_LANG_MODULE['Description'] = 'Kuvaus';
$_COS_LANG_MODULE['Submit'] = 'Esittää';
$_COS_LANG_MODULE['Edit tag'] = 'Muokkaa tunnistetta';
$_COS_LANG_MODULE['Update'] = 'Päivitys';
$_COS_LANG_MODULE['Main tags'] = 'Tärkeimmät tunnisteet';
