<?php

$_COS_LANG_MODULE['tags_main'] = 'On tärkein tag';
$_COS_LANG_MODULE['tags_add_tags_legend'] = 'Lisää Tag';
$_COS_LANG_MODULE['tags_label_title'] = 'Otsikko';
$_COS_LANG_MODULE['tags_is_main'] = 'Tärkeimmät katto';
$_COS_LANG_MODULE['tags_label_description'] = 'Kuvaus';
$_COS_LANG_MODULE['tags_submit_update'] = 'Virkistää';
$_COS_LANG_MODULE['tags_submit_add_another'] = 'Lisää toinen tag';
$_COS_LANG_MODULE['tags_submit_add'] = 'Lisätä';
$_COS_LANG_MODULE['tags_delete_tags_legend'] = 'Poista tunniste';
$_COS_LANG_MODULE['tags_submit_delete'] = 'Poistaa';
$_COS_LANG_MODULE['Tags has been deleted!'] = 'Tunnisteet on poistettu!';
$_COS_LANG_MODULE['Not sufficient privileges. Super user is required'] = 'Ei riittäviä käyttöoikeuksia. Super Käyttäjä on velvollinen';
$_COS_LANG_MODULE['tags_error_no_title'] = 'Ei otsikkoa';
$_COS_LANG_MODULE['tags_added_tag_action_message'] = 'Tag lisätään';
$_COS_LANG_MODULE['tags_updated_tag_action_message'] = 'Tag päivitetään';
$_COS_LANG_MODULE['tags_deleted_tag_action_message'] = 'Tag poistetaan';
$_COS_LANG_MODULE['tags_admin_edit'] = 'Muokata';
$_COS_LANG_MODULE['tags_admin_delete'] = 'Poistaa';
$_COS_LANG_MODULE['tags_label'] = 'Tunnisteet';
$_COS_LANG_MODULE['Tags'] = 'Tunnisteet';
