<?php

$_COS_LANG_MODULE['tags_delete_tags_legend'] = 'Ta bort etikett';
$_COS_LANG_MODULE['tags_submit_delete'] = 'Radera';
$_COS_LANG_MODULE['tags_add_tags_legend'] = 'Lägg tagg';
$_COS_LANG_MODULE['tags_label_title'] = 'Titel';
$_COS_LANG_MODULE['tags_is_main'] = 'Huvudsaklig tagg';
$_COS_LANG_MODULE['tags_label_description'] = 'Beskrivning';
$_COS_LANG_MODULE['tags_submit_add_another'] = 'Lägg annan';
$_COS_LANG_MODULE['tags_submit_add'] = 'Lägg';
$_COS_LANG_MODULE['tags_submit_update'] = 'Uppdatera';
$_COS_LANG_MODULE['tags_main'] = 'Nyckelbrickor';
$_COS_LANG_MODULE['tags_error_no_title'] = 'Ingen titel';
$_COS_LANG_MODULE['tags_added_tag_action_message'] = 'Tag Added';
$_COS_LANG_MODULE['tags_updated_tag_action_message'] = 'Tag Uppdaterat';
$_COS_LANG_MODULE['tags_deleted_tag_action_message'] = 'Tag utgår';
$_COS_LANG_MODULE['tags_admin_edit'] = 'Redigera';
$_COS_LANG_MODULE['tags_admin_delete'] = 'Radera';
