<?php

$_COS_LANG_MODULE['tags_error_no_title'] = 'Ingen titel';
$_COS_LANG_MODULE['Add another'] = 'Lägg till en annan';
$_COS_LANG_MODULE['Tag has been added'] = 'Tag har lagts';
$_COS_LANG_MODULE['Tag has been updated'] = 'Tag har uppdaterats';
$_COS_LANG_MODULE['Tag has been deleted'] = 'Tag har tagits bort';
$_COS_LANG_MODULE['Edit'] = 'Redigera';
$_COS_LANG_MODULE['Delete'] = 'Radera';
$_COS_LANG_MODULE['tags_label'] = 'Taggar';
$_COS_LANG_MODULE['Tags'] = 'Taggar';
$_COS_LANG_MODULE['Tags has been deleted!'] = 'Tags har blivit borttagen!';
$_COS_LANG_MODULE['Not sufficient privileges. Super user is required'] = 'Inte tillräcklig behörighet. Superanvändare krävs';
$_COS_LANG_MODULE['Delete tag'] = 'Radera tagg';
$_COS_LANG_MODULE['Add a tag'] = 'Lägg till en tagg';
$_COS_LANG_MODULE['Title'] = 'Titel';
$_COS_LANG_MODULE['Is a main tag'] = 'Är en huvud tagg';
$_COS_LANG_MODULE['Description'] = 'Beskrivning';
$_COS_LANG_MODULE['Submit'] = 'Skicka';
$_COS_LANG_MODULE['Edit tag'] = 'Redigera etikett';
$_COS_LANG_MODULE['Update'] = 'Uppdatera';
$_COS_LANG_MODULE['tags_main'] = 'Är huvud tag';
